set-msoluserpassword -userprincipalname rpelletier@itslowell.com -newpassword ITSRyan433! -forcechangepassword 0
set-msoluserpassword -userprincipalname jchilds@itslowell.com -newpassword ITSJim674! -forcechangepassword 0
set-msoluserpassword -userprincipalname tignatowicz@itslowell.com -newpassword ITSTim564! -forcechangepassword 0
set-msoluserpassword -userprincipalname sallard@itslowell.com -newpassword ITSShawn678! -forcechangepassword 0
set-msoluserpassword -userprincipalname echambers@itslowell.com -newpassword ITSEdward123! -forcechangepassword 0
set-msoluserpassword -userprincipalname dring@itslowell.com -newpassword ITSDave234! -forcechangepassword 0
set-msoluserpassword -userprincipalname crichards@itslowell.com -newpassword ITSColin654! -forcechangepassword 0
set-msoluserpassword -userprincipalname dlarose@itslowell.com -newpassword ITSDenis998! -forcechangepassword 0
set-msoluserpassword -userprincipalname mmuller@itslowell.com -newpassword ITSMatt976! -forcechangepassword 0
set-msoluserpassword -userprincipalname pparrott@itslowell.com -newpassword ITSPatricia943! -forcechangepassword 0
set-msoluserpassword -userprincipalname bantifonario@itslowell.com -newpassword ITSBarbara932! -forcechangepassword 0
set-msoluserpassword -userprincipalname dchamberlain@itslowell.com -newpassword ITSDonna865! -forcechangepassword 0
set-msoluserpassword -userprincipalname leo@itslowell.com -newpassword ITSLeo834! -forcechangepassword 0
set-msoluserpassword -userprincipalname pchilds@itslowell.com -newpassword ITSPam745! -forcechangepassword 0
set-msoluserpassword -userprincipalname ddonnelly@itslowell.com -newpassword ITSDanielle732! -forcechangepassword 0
set-msoluserpassword -userprincipalname lbodnar@itslowell.com -newpassword ITSLinda345! -forcechangepassword 0
set-msoluserpassword -userprincipalname icurrier@itslowell.com -newpassword ITSIan233! -forcechangepassword 0
set-msoluserpassword -userprincipalname ecelli@itslowell.com -newpassword ITSEdward232! -forcechangepassword 0
set-msoluserpassword -userprincipalname tstimson@itslowell.com -newpassword ITSTim665! -forcechangepassword 0Connec