Add-RecipientPermission rpelletier@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission jchilds@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission tignatowicz@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission sallard@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission echambers@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission dring@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission crichards@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission dlarose@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission mmuller@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission pparrott@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission bantifonario@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission dchamberlain@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission leo@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission pchilds@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission ddonnelly@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission lbodnar@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission icurrier@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission ecelli@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com
Add-RecipientPermission tstimson@itslowell.com -AccessRights SendAs -Trustee sqlmail@itslowell.com